In [48]:
import pandas as pd
from pandas import DataFrame
import numpy as np
from matplotlib.patches import Rectangle
import matplotlib.pyplot as plt

In [49]:
df = pd.read_csv('Result-Pingan-from-20110101-to-20181118.csv')
df.head()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,ave_change,pred_ave_change,real_trend,pred_trend
0,601318.SH,20170428,37.90,38.07,37.61,37.96,37.82,0.14,0.37,678663.87,2568647.819,-0.046667,-0.007615,1,1
1,601318.SH,20170502,37.80,38.38,37.80,37.91,37.96,-0.05,-0.13,619325.39,2359210.184,-0.216667,-0.070226,0,0
2,601318.SH,20170503,37.95,38.28,37.82,38.00,37.91,0.09,0.24,505383.86,1920918.772,-0.070000,-0.216266,0,0
3,601318.SH,20170504,37.95,38.10,37.73,37.82,38.00,-0.18,-0.47,548573.55,2080732.893,0.056667,-0.002267,0,0
4,601318.SH,20170505,37.70,37.86,37.20,37.26,37.82,-0.56,-1.48,623979.60,2337681.712,0.860000,0.210840,1,0

In [50]:
df.head(8)

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,ave_change,pred_ave_change,real_trend,pred_trend
0,601318.SH,20170428,37.90,38.07,37.61,37.96,37.82,0.14,0.37,678663.87,2568647.819,-0.046667,-0.007615,1,1
1,601318.SH,20170502,37.80,38.38,37.80,37.91,37.96,-0.05,-0.13,619325.39,2359210.184,-0.216667,-0.070226,0,0
2,601318.SH,20170503,37.95,38.28,37.82,38.00,37.91,0.09,0.24,505383.86,1920918.772,-0.070000,-0.216266,0,0
3,601318.SH,20170504,37.95,38.10,37.73,37.82,38.00,-0.18,-0.47,548573.55,2080732.893,0.056667,-0.002267,0,0
4,601318.SH,20170505,37.70,37.86,37.20,37.26,37.82,-0.56,-1.48,623979.60,2337681.712,0.860000,0.210840,1,0
5,601318.SH,20170508,37.26,38.12,37.24,37.79,37.26,0.53,1.42,952932.43,3609995.304,0.660000,0.611569,1,1
6,601318.SH,20170509,37.71,38.08,37.71,37.99,37.79,0.20,0.53,595182.93,2258188.097,0.986667,0.581645,1,1
7,601318.SH,20170510,38.03,40.05,38.01,39.84,37.99,1.85,4.87,1589203.71,6249692.993,0.353333,0.268698,1,1

In [51]:
df.iloc[150]

ts_code              601318.SH
trade_date            20171206
open                      70.9
high                      71.1
low                         68
close                     69.4
pre_close                 71.2
change                    -1.8
pct_chg                  -2.53
vol                1.24561e+06
amount             8.68333e+06
ave_change             1.28333
pred_ave_change       0.853706
real_trend                   1
pred_trend                   1
Name: 150, dtype: object

In [ ]:
real_trend = df['real_trend']
new_pred_trend = df['pred_trend']

In [ ]:
temp_df = real_trend - pred_trend
temp_df.value_counts()

In [59]:
df = pd.read_csv('Result-Pingan-from-20110101-to-20181118-Copy1.csv')
df.head()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,ave_change,pred_ave_change,real_trend,pred_trend
0,601318.SH,20170428,37.90,38.07,37.61,37.96,37.82,0.14,0.37,678663.87,2568647.819,-0.046667,-0.007615,1,1
1,601318.SH,20170502,37.80,38.38,37.80,37.91,37.96,-0.05,-0.13,619325.39,2359210.184,-0.216667,-0.070226,0,0
2,601318.SH,20170503,37.95,38.28,37.82,38.00,37.91,0.09,0.24,505383.86,1920918.772,-0.070000,-0.216266,0,0
3,601318.SH,20170504,37.95,38.10,37.73,37.82,38.00,-0.18,-0.47,548573.55,2080732.893,0.056667,-0.002267,0,0
4,601318.SH,20170505,37.70,37.86,37.20,37.26,37.82,-0.56,-1.48,623979.60,2337681.712,0.860000,0.210840,1,0

In [ ]:
pred_trend = df['real_trend']

In [55]:
xlims = (0,len(real_trend)+20)
ylims = (0, 300)

In [56]:
def plot_renko(data, brick_size):
    fig = plt.figure(figsize=(20,10))
    fig.clf()
    axes = fig.gca()   
    prev_num = 0
    for index, number in enumerate(data):
#         print(index, number)
        if number == 1:
            facecolor='red'
        elif number == 0:
            facecolor='blue'
        else:
            facecolor='green'

        prev_num += number

        renko = Rectangle(
            (index, prev_num * brick_size+100), 1, brick_size,
            facecolor=facecolor, alpha=0.5
        )
        axes.add_patch(renko)
    plt.xlim(xlims)
    plt.ylim(ylims)
#     plt.show()

In [58]:
%matplotlib qt
fig = plt.figure(figsize=(20,10))
fig.clf()
axes = fig.gca()   
prev_num = 0
data = real_trend
brick_size = 4
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+80), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)

prev_num = 0
data = new_pred_trend
brick_size = 4
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+30), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)    

    
prev_num = 0
data = pred_trend
brick_size = 4
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+30), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)   
    
    
axes.get_yaxis().set_visible(False)
plt.xlabel('Days', fontsize=18)
plt.tick_params(axis='both', which='major', labelsize=30)
# plt.ylabel('Trend Prediction', fontsize=18)
plt.xlim(xlims)
plt.ylim(ylims)

(0, 300)

In [10]:
df = pd.read_csv('Result-SVR&Random-Pingan-from-20080101-to-20181118.csv')
df.head()

,open,high,low,pre_close,change,pct_chg,vol,amount,close,ave_change,pred_change,real_trend,pred_trend,random_trend
0,37.49,38.26,37.44,37.51,0.31,0.83,1250054.58,4732657.328,37.82,0.060000,-0.171518,1,1,-1
1,37.90,38.07,37.61,37.82,0.14,0.37,678663.87,2568647.819,37.96,-0.046667,0.020798,0,0,1
2,37.80,38.38,37.80,37.96,-0.05,-0.13,619325.39,2359210.184,37.91,-0.216667,0.003663,0,0,0
3,37.95,38.28,37.82,37.91,0.09,0.24,505383.86,1920918.772,38.00,-0.070000,0.043405,0,0,1
4,37.95,38.10,37.73,38.00,-0.18,-0.47,548573.55,2080732.893,37.82,0.056667,-0.008534,0,0,1

In [14]:
# real_trend = df['real_trend']
svr_pred_trend = df['pred_trend']
random_trend = df['random_trend']

In [15]:
temp_df = real_trend - svr_pred_trend
temp_df.value_counts()

 0.0    121
 1.0    109
-1.0    102
-2.0     31
 2.0     17
dtype: int64

In [16]:
%matplotlib qt
fig = plt.figure(figsize=(20,10))
fig.clf()
axes = fig.gca()   
prev_num = 0
data = real_trend
brick_size = 3
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+150), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)

prev_num = 0
data = pred_trend
brick_size = 3
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+90), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)    

    
prev_num = 0
data = svr_pred_trend
brick_size = 3
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+30), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)   
    
# prev_num = 0
# data = random_trend
# brick_size = 2
# for index, number in enumerate(data):
# #         print(index, number)
#     if number == 1:
#         facecolor='red'
#     elif number == 0:
#         facecolor='blue'
#     else:
#         facecolor='green'

#     prev_num += number

#     renko = Rectangle(
#         (index, prev_num * brick_size+100), 1, brick_size,
#         facecolor=facecolor, alpha=0.5
#     )
#     axes.add_patch(renko)   
axes.get_yaxis().set_visible(False)
plt.xlabel('Days', fontsize=23)
plt.tick_params(axis='both', which='major', labelsize=30)
# plt.ylabel('Trend Prediction', fontsize=18)
plt.xlim(xlims)
plt.ylim(ylims)

(0, 300)

In [3]:
import pandas as pd
df = pd.read_csv('Result-Pingan-from-20110101-to-20181118.csv')
df.head()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,ave_change,pred_ave_change,real_trend,pred_trend
0,601318.SH,20170428,37.90,38.07,37.61,37.96,37.82,0.14,0.37,678663.87,2568647.819,-0.046667,-0.007615,1,1
1,601318.SH,20170502,37.80,38.38,37.80,37.91,37.96,-0.05,-0.13,619325.39,2359210.184,-0.216667,-0.070226,0,0
2,601318.SH,20170503,37.95,38.28,37.82,38.00,37.91,0.09,0.24,505383.86,1920918.772,-0.070000,-0.216266,0,0
3,601318.SH,20170504,37.95,38.10,37.73,37.82,38.00,-0.18,-0.47,548573.55,2080732.893,0.056667,-0.002267,0,0
4,601318.SH,20170505,37.70,37.86,37.20,37.26,37.82,-0.56,-1.48,623979.60,2337681.712,0.860000,0.210840,1,0

In [11]:
real_trend = df['real_trend'][:150]
pred_trend = df['pred_trend'][:150]

In [12]:
temp_list = []
temp_df =  real_trend - pred_trend
for i in range(0, len(temp_df)):
    temp_list.append([i, temp_df[i]])

In [13]:
%matplotlib qt
plt.clf()
# plt.figure()
plt.scatter( *zip(*temp_list), )
# plt.scatter(real_df.index.values, pred_df[0],color='blue', marker='^')
# plt.scatter(real_df.index.values, real_df[0],color='red', marker='.')
plt.title('Trend Prediction Accuracy of 601318SH' )
plt.xlabel('Days')
plt.ylabel('Trend Prediction')
plt.show()

In [14]:
temp_list = []
temp_df =  real_trend[0] - pred_df[0]
for i in range(0, len(temp_df)):
    temp_list.append([i, temp_df[i]])

NameError: name 'pred_df' is not defined

In [14]:
temp_df.value_counts()

 0    74
 1    48
-1    27
-2     1
dtype: int64