In [2]:
import pandas as pd
from pandas import DataFrame
import numpy as np
from matplotlib.patches import Rectangle
import matplotlib.pyplot as plt

In [3]:
df1 = pd.read_csv('1-Result-Vanke-from-20110701-to-20181118.csv')
df2 = pd.read_csv('2-Result-Vanke-from-20110701-to-20181118.csv')
df3 = pd.read_csv('3-Result-Vanke-from-20110701-to-20181118.csv')
df4 = pd.read_csv('4-Result-Vanke-from-20110701-to-20181118.csv')
df5 = pd.read_csv('5-Result-Vanke-from-20110701-to-20181118.csv')

In [4]:
df1.head()

,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,vol,amount,ave_change,pred_ave_change,real_trend,pred_trend
0,000002.SZ,20170714,24.45,24.83,24.36,24.59,24.43,0.16,0.65,201797.31,495832.293,0.253333,0.240880,1,1
1,000002.SZ,20170718,25.58,25.80,24.88,25.30,24.59,0.71,2.89,791833.77,2004962.442,-0.173333,0.158183,-1,1
2,000002.SZ,20170719,24.85,26.06,24.43,25.14,25.30,-0.16,-0.63,1008070.70,2526934.175,-0.446667,-0.258133,-1,-1
3,000002.SZ,20170720,24.85,25.64,24.73,25.35,25.14,0.21,0.84,633677.05,1598967.701,-0.696667,-0.335284,-1,-1
4,000002.SZ,20170721,25.19,25.64,24.65,24.78,25.35,-0.57,-2.25,477662.55,1195588.636,-0.453333,-0.310199,-1,-1

In [5]:
df2.head()

,Unnamed: 0,ts_code,trade_date,open,high,low,close,pre_close,change,pct_chg,...,kdj_d,kdj_j,bias,rsi,roc,psy,ave_change,pred_ave_change,real_trend,pred_trend
0,1317,000002.SZ,20170714,24.45,24.83,24.36,24.59,24.43,0.16,0.65,...,219.467860,-43.608937,-0.189420,46.168224,-2.318015,50.000000,0.253333,0.103304,1,1
1,1318,000002.SZ,20170718,25.58,25.80,24.88,25.30,24.59,0.71,2.89,...,192.626338,31.577202,2.643857,51.186441,1.304348,50.000000,-0.173333,-0.000519,-1,0
2,1319,000002.SZ,20170719,24.85,26.06,24.43,25.14,25.30,-0.16,-0.63,...,177.916694,89.658831,1.936138,51.448041,2.267303,50.000000,-0.446667,-0.094519,-1,0
3,1320,000002.SZ,20170720,24.85,25.64,24.73,25.35,25.14,0.21,0.84,...,169.943886,122.107040,2.517440,56.866197,5.877712,58.333333,-0.696667,-0.395114,-1,-1
4,1321,000002.SZ,20170721,25.19,25.64,24.65,24.78,25.35,-0.57,-2.25,...,157.811880,85.019841,-0.097430,58.303249,0.968523,58.333333,-0.453333,-0.323922,-1,-1

In [6]:
df3.head()

,Unnamed: 0,ts_code,trade_date,open_x,high_x,low_x,close_x,pre_close_x,change_x,pct_chg_x,...,low_y,pre_close_y,change_y,pct_chg_y,vol_y,amount_y,ave_change,pred_ave_change,real_trend,pred_trend
0,1317,000002.SZ,20170714,24.45,24.83,24.36,24.59,24.43,0.16,0.65,...,3204.8529,3218.1632,4.2536,0.1322,160126773.0,174312138.1,0.253333,0.204950,1,1
1,1318,000002.SZ,20170718,25.58,25.80,24.88,25.30,24.59,0.71,2.89,...,3150.1284,3176.4648,11.1024,0.3495,190623060.0,196452361.5,-0.173333,0.053219,-1,0
2,1319,000002.SZ,20170719,24.85,26.06,24.43,25.14,25.30,-0.16,-0.63,...,3179.7300,3187.5672,43.4090,1.3618,272420726.0,269771019.5,-0.446667,-0.134651,-1,-1
3,1320,000002.SZ,20170720,24.85,25.64,24.73,25.35,25.14,0.21,0.84,...,3225.4328,3230.9762,13.8885,0.4299,232108392.0,245825421.9,-0.696667,-0.427589,-1,-1
4,1321,000002.SZ,20170721,25.19,25.64,24.65,24.78,25.35,-0.57,-2.25,...,3231.9556,3244.8647,-6.8830,-0.2121,206003251.0,221956909.9,-0.453333,-0.382443,-1,-1

In [7]:
df4.head()

,Unnamed: 0,ts_code,trade_date,open_x,high_x,low_x,close_x,pre_close_x,change_x,pct_chg_x,...,kdj_d,kdj_j,bias,rsi,roc,psy,ave_change,pred_ave_change,real_trend,pred_trend
0,1317,000002.SZ,20170714,24.45,24.83,24.36,24.59,24.43,0.16,0.65,...,219.467860,-43.608937,-0.189420,46.168224,-2.318015,50.000000,0.253333,0.043812,1,1
1,1318,000002.SZ,20170718,25.58,25.80,24.88,25.30,24.59,0.71,2.89,...,192.626338,31.577202,2.643857,51.186441,1.304348,50.000000,-0.173333,0.025637,-1,0
2,1319,000002.SZ,20170719,24.85,26.06,24.43,25.14,25.30,-0.16,-0.63,...,177.916694,89.658831,1.936138,51.448041,2.267303,50.000000,-0.446667,-0.173562,-1,-1
3,1320,000002.SZ,20170720,24.85,25.64,24.73,25.35,25.14,0.21,0.84,...,169.943886,122.107040,2.517440,56.866197,5.877712,58.333333,-0.696667,-0.417943,-1,-1
4,1321,000002.SZ,20170721,25.19,25.64,24.65,24.78,25.35,-0.57,-2.25,...,157.811880,85.019841,-0.097430,58.303249,0.968523,58.333333,-0.453333,-0.393317,-1,-1

In [8]:
df5.head()

,Unnamed: 0,ts_code_x,trade_date,open_x,high_x,low_x,close_x,pre_close_x,change_x,pct_chg_x,...,kdj_d,kdj_j,bias,rsi,roc,psy,ave_change,pred_ave_change,real_trend,pred_trend
0,1317,000002.SZ,20170714,24.45,24.83,24.36,24.59,24.43,0.16,0.65,...,219.467860,-43.608937,-0.189420,46.168224,-2.318015,50.000000,0.253333,0.194019,1,1
1,1318,000002.SZ,20170718,25.58,25.80,24.88,25.30,24.59,0.71,2.89,...,192.626338,31.577202,2.643857,51.186441,1.304348,50.000000,-0.173333,0.104016,-1,1
2,1319,000002.SZ,20170719,24.85,26.06,24.43,25.14,25.30,-0.16,-0.63,...,177.916694,89.658831,1.936138,51.448041,2.267303,50.000000,-0.446667,-0.217902,-1,-1
3,1320,000002.SZ,20170720,24.85,25.64,24.73,25.35,25.14,0.21,0.84,...,169.943886,122.107040,2.517440,56.866197,5.877712,58.333333,-0.696667,-0.245509,-1,-1
4,1321,000002.SZ,20170721,25.19,25.64,24.65,24.78,25.35,-0.57,-2.25,...,157.811880,85.019841,-0.097430,58.303249,0.968523,58.333333,-0.453333,-0.260976,-1,-1

In [9]:
real_trend = df1['real_trend']
pred_trend1 = df1['pred_trend']
pred_trend2 = df2['pred_trend']
pred_trend3 = df3['pred_trend']
pred_trend4 = df4['pred_trend']
pred_trend5 = df5['pred_trend']

In [17]:
xlims = (0,len(real_trend))
ylims = (0, 630)

In [22]:
%matplotlib qt
fig = plt.figure(figsize=(20,10))
fig.clf()
axes = fig.gca()   
prev_num = 0
data = real_trend
brick_size = 2
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+570), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)

prev_num = 0
data = pred_trend1
brick_size = 2
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+470), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)    

    
prev_num = 0
data = pred_trend2
brick_size = 2
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+370), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)    
    
    
prev_num = 0
data = pred_trend3
brick_size = 2
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+270), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)    
    
    
prev_num = 0
data = pred_trend4
brick_size = 2
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+170), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)    
    
prev_num = 0
data = pred_trend5
brick_size = 2
for index, number in enumerate(data):
#         print(index, number)
    if number == 1:
        facecolor='red'
    elif number == 0:
        facecolor='blue'
    else:
        facecolor='green'

    prev_num += number

    renko = Rectangle(
        (index, prev_num * brick_size+70), 1, brick_size,
        facecolor=facecolor, alpha=0.5
    )
    axes.add_patch(renko)    
    
    
    
    

plt.tick_params(axis='both', which='major', labelsize=30)
# plt.tick_params(axis='both', which='minor', labelsize=8)
plt.xlabel('Days', fontsize=30)
plt.ylabel('Trend Prediction', fontsize=30)
plt.xlim(xlims)
plt.ylim(ylims)

(0, 630)

In [24]:
pd.set_option('display.expand_frame_repr', False)

In [23]:
df = pd.read_csv('Total-data-after-Autoencoder-dimension-reduction.csv')

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,ave_change
0,-1.246198e+08,-1.624767e+07,605322.994191,-534771.378880,-1192.570274,-99.424949,-27.775339,-1.784126,-10.406661,-2.628474,8.653167,-7.204268,30.108813,60.940383,12.617903,1.981505,-1.071563,0.477771,0.046667
1,-7.603515e+07,-1.414783e+07,-223391.883688,-295583.717229,-651.246783,-99.021349,-43.027941,-75.475923,-1.720760,-78.185458,7.904326,-3.925893,13.826128,8.918976,-16.078816,-1.740470,0.817825,0.019140,0.020000
2,-9.524888e+07,-1.499555e+07,700388.585755,-591209.025691,-1261.343344,-53.327956,-30.164170,-12.401522,-22.223717,-77.725014,0.678392,8.804532,11.821480,8.867001,-13.433207,0.466393,0.290021,0.030882,-0.006667
3,-1.046750e+08,-1.691048e+07,-330458.275464,-215077.517631,-668.117141,-50.723226,-45.400474,1.948180,-4.795344,-56.385197,-2.246018,13.574160,17.238350,-5.969432,-9.628242,-0.951568,0.511939,0.000355,-0.023333
4,-8.225343e+07,-1.641113e+07,-165579.837059,-312551.020340,-722.054412,-60.112287,-35.449947,14.736202,-11.081554,-23.533493,8.493759,-8.036328,10.730704,0.536932,-0.851757,-0.986055,0.102343,0.136171,-0.090000

In [26]:
pd.set_option('display.max_columns', 12)
df.head()

              0             1              2              3            4          5     ...             13         14        15        16        17  ave_change
0 -1.246198e+08 -1.624767e+07  605322.994191 -534771.378880 -1192.570274 -99.424949     ...      60.940383  12.617903  1.981505 -1.071563  0.477771    0.046667
1 -7.603515e+07 -1.414783e+07 -223391.883688 -295583.717229  -651.246783 -99.021349     ...       8.918976 -16.078816 -1.740470  0.817825  0.019140    0.020000
2 -9.524888e+07 -1.499555e+07  700388.585755 -591209.025691 -1261.343344 -53.327956     ...       8.867001 -13.433207  0.466393  0.290021  0.030882   -0.006667
3 -1.046750e+08 -1.691048e+07 -330458.275464 -215077.517631  -668.117141 -50.723226     ...      -5.969432  -9.628242 -0.951568  0.511939  0.000355   -0.023333
4 -8.225343e+07 -1.641113e+07 -165579.837059 -312551.020340  -722.054412 -60.112287     ...       0.536932  -0.851757 -0.986055  0.102343  0.136171   -0.090000

[5 rows x 19 columns]

In [11]:
real_trend = df['real_trend']
pred_trend = df['pred_trend']

In [12]:
temp_list = []
temp_df =  real_trend - pred_trend
for i in range(0, len(temp_df)):
    temp_list.append([i, temp_df[i]])

In [13]:
%matplotlib qt
plt.clf()
# plt.figure()
plt.scatter( *zip(*temp_list), )
# plt.scatter(real_df.index.values, pred_df[0],color='blue', marker='^')
# plt.scatter(real_df.index.values, real_df[0],color='red', marker='.')
plt.title('Trend Prediction Accuracy of 601318SH' )
plt.xlabel('Days')
plt.ylabel('Trend Prediction')
plt.show()

In [14]:
def plot_renko(data, brick_size):
    fig = plt.figure(figsize=(20,10))
    fig.clf()
    axes = fig.gca()   
    prev_num = 0
    for index, number in enumerate(data):
#         print(index, number)
        if number == 1:
            facecolor='red'
        elif number == 0:
            facecolor='blue'
        else:
            facecolor='green'

        prev_num += number

        renko = Rectangle(
            (index, prev_num * brick_size+100), 1, brick_size,
            facecolor=facecolor, alpha=0.5
        )
        axes.add_patch(renko)
    plt.xlim(xlims)
    plt.ylim(ylims)
#     plt.show()

NameError: name 'pred_df' is not defined